### ISSUE TITLE
Social media integration

### ISSUE THREAD

**Issue by TristanBomb** [8values/8values.github.io#10]
It would be nice if it was easier to send scores via Twitter, Facebook, BBCode, or other similar mechanisms, for instance with share buttons. This would probably require changing how the image is generated, though.

**Comment by Berkmann18** [comment]
Have you tried looking at FB/Twitter/G+/... APIs for this?

**Comment by TristanBomb** [comment]
I have not yet looked at the APIs for this. Currently, the image is generated via a JS canvas; I think an alternative means would be necessary to make the images shareable, but I could be wrong.

**Comment by Berkmann18** [comment]
Well, one way to go about this (as suggested in another issue I've seen) is that it could be saved to an image that then can be saved/shared.

**Comment by Genora51** [comment]
Following #7 (fixed by #104) this is less of an issue as the image can now be properly shared.

It might be worth looking into the [Web Share API](https://developers.google.com/web/updates/2016/09/navigator-share) (still [not widely supported](https://caniuse.com/#feat=web-share), sadly) for better control of results sharing.

Until that happens, the current solution (using a PNG to display the image rather than a canvas) works pretty well.
