### ISSUE TITLE
Add open source license

### ISSUE THREAD

**Issue by zachoooo** [8values/8values.github.io#15]
Attaching an MIT license would be great so that this can be safely used by others.

**Comment by TristanBomb** [comment]
I didn't really expect it to get so popular. Yes, that is a good idea.

**Comment by zachoooo** [comment]
I'm already beginning some changes so I can use it for a community that I'm part of so I'd love to see a permissive license added <3

**Comment by elifoster** [comment]
This is a good idea.

Legal stuff: I believe legally you're supposed to get consent from all contributors when changing the license. So, since I've contributed, I hereby state that I consent to changing the license to any of the open licenses listed at opensources.org (Apache License 2.0, BSD 3, BSD 2, GNU GPL, GNU LGPL, MIT, Mozilla Public License 2.0, Common Development and Distribution License, Eclipse Publication License) as well as the Unlicense and the Creative Commons 0 license.

**Comment by TristanBomb** [comment]
Ah, thanks, I'm not particularly great with legal stuff. The license has been changed to MIT.
