### ISSUE TITLE
I have issue with "Wars do not need to be justified to other countries."

### ISSUE THREAD

**Issue by mitar** [8values/8values.github.io#25]
Because to me the issue is that I do not think wars can be justified at all. So I cannot agree or disagree with this.

**Comment by TristanBomb** [comment]
It seems like you'd Strongly Disagree - I'm not sure I see the issue. Even if you think no wars are justified, it's better to justify it than to not, right?

**Comment by mitar** [comment]
No, the whole concept that you can justify wars is problematic. It is not OK if they are justified (strongly disagree) or if they are not (strongly agree).

**Comment by gus-morales** [comment]
I understand the current wording presenting a problem to the pacifist side of the spectrum. Choosing "Strongly Disagree" might be read as "Wars DO need to be justified to other countries.", which sounds as beligerant as the "Strongly Agree" option. 

Maybe "Wars are sometimes justifiable" achieves the same effect in the quiz?

**Comment by elifoster** [comment]
Tbh, if I were a pacifist, I would have just selected neutral/unsure for this question.

**Comment by mitar** [comment]
If the question was "Raping 5 years old children does not need to be justified." you would be neutral on that question?

**Comment by elifoster** [comment]
I'm assuming neutral/unsure results in no effect on my overall score. If that's the case, then things which my opinion does not fit within the agree/disagree binary, I would do that. That would be the case for the 5 year olds question because I don't think it is acceptable, nor do I think it is justifiable. Isn't that precisely where you stand on wars?

**Comment by mitar** [comment]
Hm, I am not sure if negation of the question means that it is acceptable? To me it is: Does war has to be justified or does it not? And to me the answer is that it is not the question if it has to be justified or not, but that it cannot be justified at all.

**Comment by gus-morales** [comment]
But I am assuming that the "Unsure" option is the less desirable one to predict axes values, since it gives zero weight. Basically the algorithm works the best the less "unsure" the person is (which is why I would not mix it with the "Neutral" option, but that is another topic).

**Comment by jaybz** [comment]
For the purposes of the axes values, Strongly Disagree is probably what you should answer here. You can think of it in the sense that wars should absolutely require justification combined with the thought that there will never be sufficient justification in the first place. Unsure sounds like it means that you think there are cases where war is ok without justification and that it just depends entirely on each situation's circumstances alone and I'm pretty sure there's no way for the quiz to distinguish between the two. ;-)

Also note that when something is justified, it does not necessarily mean it is acceptable. It may mean that all other possible alternatives just happen to be worse.

**Comment by mitar** [comment]
I think the fact that different people are suggesting that pacifists should select different answers is showing how tricky is to answer this question as a pacifistic.

**Comment by jaybz** [comment]
The different suggestions are due to the fact that we are looking at this from the scoring perspective. And scoring these is certainly tricky. The unfortunate nature of quizzes like this, is that your situation will always come up. And as gus-morales said, the less Unsure answers you provide, the better these quizzes work. This is addressed by asking the respondent to answer with the closest answer. It seems that Strongly Disagree is the closest. That said, Unsure is the safer option because it doesn't affect any axis at all, and non-Unsure answers may affect more than just one. Your uncompromising (for lack of a better word atm) view on war makes me think that it is more important to reflect this on the Diplomacy axis than it is to prevent other possible effects related to the question.
