### ISSUE TITLE
"Gun ownership should be prohibited for those without a valid reason."

### ISSUE THREAD

**Issue by Strtg** [8values/8values.github.io#4]
The points for "Gun ownership should be prohibited for those without a valid reason." should add liberty instead of oppression. And I don't know why it adds militarism.

**Comment by mason-bially** [comment]
I think the implication is that a "reason" would imply like Scandinavian countries where only members of the military have a reason to own guns.

**Comment by ggvaldez** [comment]
I would add that "valid reason" can be quite vague. And people can disagree with that statement because they are more pro-gun or more anti-gun. Maybe change to something like "for most people" for less ambiguity?

**Comment by TristanBomb** [comment]
I'm sorry, but I'm not sure how prohibiting ownership of something is a "liberty" stance. I personally support gun controls, but I fully acknowledge that this somewhat impedes on personal liberties.

Prohibiting gun ownership does *not* add to the Might value, it actually adds to the Peace value. The positive values on the JS file are Equality, Peace, Liberty, and Progress, which alternate sides on the results page in order to keep the colors looking good.

**Comment by TristanBomb** [comment]
Since it seems nobody else has commented on this and I don't see a problem, I'm closing this issue.
