### ISSUE TITLE
Universal Healthcare is not Single-Payer

### ISSUE THREAD

**Issue by waterafternoon** [8values/8values.github.io#49]
The question is problematic because single-payer is a type of universal healthcare, but not all universal healthcare systems are single-payer. See: every UH country in europe.

**Comment by hsoj95** [comment]
While you are correct, one only needs to look to ObamaCare to see a non-single-payer health system, single-payer health systems are easily the most progressive/socialist form of a universal health system. It also is the most easily definable, in my view, for the purposes of the survey. Trying to narrow down exactly what type of health system people approve of would take multiple questions, and increase the difficulty of the survey overall.

**Comment by waterafternoon** [comment]
> single-payer health systems are easily the most progressive/socialist form of a universal health system.

Is that what the question is supposed to indicate? Being progressive/socialist, not egalitarian? Mainstream economists as a whole support universal healthcare generally because it helps provide equal opportunity, but don't support single payer because it's a terrible policy.

Having single-payer is akin to giving the minimum wage question a "$15 an hour" qualifier.

As in, many support a minimum wage at a certain level because it helps the poor, but adding a $15 is specific policy that's entirely unreasonable by people who want to help the poor, but know that it's too high to help more than hurt.

**Comment by hsoj95** [comment]
Again, you're not wrong! The problem is phrasing the question in a way that is specific. Single-payer universal health care is a specific form of it. Just saying universal health care is not very specific, with raises some issues. It also depends on what view you come at it from. A capitalist, like myself, will not view any form of universal health care positively, while a progressive/socialist will view it positively. Someone who isn't a progressive/socialist, but still of an egalitarian mind might be ok with a mild form of universal health care, but maybe not Single-Payer. 

This is where problems arise with just calling it "Universal Health Care". The issue boils down to how much are we talking about? By being specific and saying "Single-Payer Universal Health Care" you are specifically saying, "Do you agree with this specific thing", with is important for the purposes of the survey. If you just call it "Universal Health Care", you raise an issue over what type of system we are talking about. Are we talking a very mild form like Obamacare or are we talking a Single-Payer system like the NHS in Britain? By leaving the question vague, it raises an issue of people who fall somewhere in the middle either not knowing what answer to choose and just selecting neutral, or choosing the wrong answer based on the presumption that it is either more or less of the system than they support. This won't effect the Capitalist and the progressives/socialists, as their answers won't change, but it will negatively effect those who fall somewhere in the middle.

(Note: I didn't actually make the answers for the quiz, as I have only recently started contributing here. But I do believe that's what the admin was going for! This is also my view on the issue as well! Hope this answered your concerns! :slightly_smiling_face: )

**Comment by TristanBomb** [comment]
This is an old issue, but I'm going through these to clean up the issue list. @hsoj95 is right on the money here, and since there's no longer active discussion on the issue, I'm going to close this.
