### ISSUE TITLE
Problems with libertarian socialism/anarchism ideologies

### ISSUE THREAD

**Issue by brmbrmcar** [8values/8values.github.io#58]
Communism is a form of socialism. Libertarian communism and anarcho-communism are exactly the same thing. Also, anarcho-communism is pretty much impossible to get. It seems apparent to me that you have no idea what these terms mean.

And there are a few statist-biased questions, which make anarchists more right wing or more authoritarian.

**Comment by TristanBomb** [comment]
Sorry for not commenting on this far sooner.

First, libertarian communism and anarcho-communism are _not_ the same thing - "libertarian" leaves room for a minimal state, while "anarchist" implies the complete lack of a state. Certain ideologies are quite difficult to get, which is an issue that will be looked at (eventually) with the ideology rework.

Finally, you're absolutely right that the quiz is not well-suited for anarchists. However, do understand that because anarchism is so vastly different from other ideologies (in that most ideologies see at least some role for the state), it's nearly impossible to create a quiz that covers both _and_ refers to specific issues. As it stands, "anarchism" in the 8values test is more-or-less being used to refer to high Liberty values.

**Comment by brmbrmcar** [comment]
Anarchism is the abolition of unjustified hierarchy, not just anti-state. And besides, you should just say "social anarchism" or something because there is no way to tell what kind of anarchist you are from this test. Or tell what kind of socialist you are.

And as an anarchist, I can tell you that "libertarian" and "anarcho" (for us) are used synonymously.
