### ISSUE TITLE
"No authority should be left unquestioned." is confusing

### ISSUE THREAD

**Issue by zcyzcy88** [8values/8values.github.io#64]
1. What is the "left" mean? Keep or abandon?
2. Double negation is confusing, please change to direct description.

**Comment by locoluis** [comment]
I understand this statement as a necessity to question all authority. To recognize that humanity is flawed, that we're prone to commit mistakes and that authorities aren't an exception. No one should be obeyed just because.

It's a "should", not a "must", because people should not go out of their way to question all authority; rather, it means that there's no authority is immune to scrutiny.

Disagreeing with this statement implies the opinion that some authority is not to be questioned; as an extreme example, this may be justified on the grounds of a divine authority in a theocracy, or a "great leader" in a state ideology.

**Comment by hsoj95** [comment]
I do agree that this question could be left open to some confusion with the double negative. The question should most likely be "All authority should be questioned." This would help clear up any major confusion that could arise surrounding the question.
